name: tar
description: Memory-efficient, streaming implementation of the tar file format
version: 0.4.1
repository: https://github.com/simolus3/tar/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.6.0
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  charcode: ^1.2.0
  extra_pedantic: ^1.4.0
  path: ^1.8.0
  test: ^1.17.4
